# Generated by Django 5.2.8 on 2025-11-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='writings/images')),
                ('title', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=300)),
                ('recommended_minutes', models.PositiveSmallIntegerField(default=20, help_text='Tavsiya etilgan vaqt (daqiqa)')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=300)),
                ('recommended_minutes', models.PositiveSmallIntegerField(default=40, help_text='Tavsiya etilgan vaqt (daqiqa)')),
            ],
        ),
    ]
