# Generated by Django 5.2.8 on 2025-11-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingcheck',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
