# Generated by Django 5.2.8 on 2025-11-11 12:15

import writing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_writingtask_writingsubmission_writingevaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsubmission',
            name='end_time',
            field=models.DateTimeField(default=writing.models.one_hour_later),
        ),
    ]
